### ISSUE TITLE
Fix some problems

### ISSUE THREAD

**Issue by jeroen** [ar-puuk/ar-puuk.r-universe.dev#1]
Many of the URLs in your packages.json are not git repos. You can only include git repos in the list. Can you have a look at the error logs here and remove the broken ones: https://github.com/r-universe/ar-puuk/actions/workflows/sync.yml

**Comment by ar-puuk** [comment]
Thanks for pointing out the issue. I (think I have) resolved the URLs and hope this fixes the issue.

Thanks and much appreciated.
